export const name = "Jyotirmoy Bandhapadhayaya";
export const github_url = "https://github.com/bravo68web";
export const twitter_url = "https://twitter.com/bravo68web";
export const linkedin_url = "https://linkedin.com/in/bravo68web";
export const mastodon_url = "https://fosstodon.org/@bravo68web/";
export const email = "mailto:hi@b68.dev";
export const instagram_url = "https://instagram.com/bravo68web";
export const hackthebox_url = "https://app.hackthebox.com/profile/1367733";
export const phone = "";
export const address = "";
export const website = "https://b68.dev";
export const resume_url = "https://s.b68.dev/resume";
export const facebook_url = "https://www.facebook.com/Bravo68Web/";
export const discord_id = "457039372009865226";
export const avatar_id = "b9e91dcc8e658eb1ebf24299b7bec733";
export const discord_profile = "";

export const job_exp_5 = {
	name: "DF Tech Community",
	info: "Freelance community for developers and designers",
	role: "Wordpress Manager + Hosting Manager",
	description:
		"I was the Wordpress Manager and Hosting Manager of the DF Tech Community. I was responsible for managing the Wordpress website and the hosting of the website. I was also responsible for managing the hosting of the community's Discord bot.",
	start_date: "2018-04-05",
	end_date: "2019-12-24",
	logo: "/images/companies/DFTechsLogo.png",
	website: "",
	techstack: [
		"Wordpress",
		"PHP",
		"MySQL",
		"Apache",
		"Linux",
		"Discord.js",
		"AWS",
		"Alibaba Cloud",
	],
};
export const job_exp_4 = {
	name: "Engineer's Cradle",
	info: "EdTech Company catering Engineering Students",
	role: "Full Stack Cloud Developer",
	description:
		"I was a CTO DevOps and Full Stack Developer at Engineer's Cradle. Being one of the founding members of the company, I was responsible for managing the comapany's website and creating initial MVP for onboarding students for the platform. I lead the backend development team and was responsible for managing the backend infrastructure of the company.",
	start_date: "2021-04-01",
	end_date: "2022-05-15",
	logo: "https://engineerscradle.com/assets/Logo_lg.svg",
	techstack: [
		"ReactJS",
		"NextJS",
		"NodeJS",
		"Express",
		"MongoDB",
		"AWS",
		"Redis",
		"TailwindCSS",
		"Docker",
	],
	website: "https://engineerscradle.com",
};
export const job_exp_3 = {
	name: "Hybr1d.io",
	role: "SDE Backend Developer Intern",
	info: "An IT Solutions company provider",
	description:
		"I was a SDE Backend Developer at Hybr1d.io. I was responsible for migrating company's backend architecture from Ruby on Rails to Typescript alongside creating microservices. I was also responsible for managing the company's backend infrastructure and creating CI/CD pipelines for the company's backend services on AWS Cloud.",
	start_date: "2022-06-01",
	end_date: "2022-12-29",
	logo: "https://safe.b68dev.xyz/4TDyZWOf.png",
	techstack: [
		"Typescript",
		"NodeJS",
		"Express",
		"PostgreSQL",
		"AWS",
		"Redis",
		"Docker",
		"ECS",
		"Jest",
		"Github Actions",
		"Hasura GQL",
	],
	website: "https://hybr1d.io",
};
export const job_exp_2 = {
	name: "Sharpsell.ai",
	role: "Site Reliability Engineer Intern",
	description:
		"I was a Site Reliability Engineer at Sharpsell. I was responsible for managing the company's infrastructure and creating CI/CD pipelines for the company's services on AWS Cloud. I was also responsible for creating the company's backend architecture, creating microservices and deploy scable solutions.",
	start_date: "2023-01-15",
	end_date: "2023-05-04",
	logo: "https://uploads-ssl.webflow.com/606c68b3010f42577120b042/638781352dfd05a38fcf756f_menu%20logo%201.png",
	techstack: [
		"AWS",
		"Python",
		"Bash",
		"Docker",
		"ECS",
		"EC2",
		"S3",
		"Lambda",
		"Cloudfront",
		"Nginx",
		"Infra Design",
	],
	website: "https://sharpsell.ai",
	info: "Sales Playbook Automation Platform helps large sales teams to scale",
};
export const job_exp_1 = {
	name: "SaaSDen",
	role: "SDE Intern",
	description:
		"I works as an founding engineer as a backend developer. I was responsible for creating the backend architecture of the company and creating microservices. I was also responsible for managing the company's backend infrastructure and creating CI/CD pipelines for the company's backend services on AWS and Azure Cloud.",
	start_date: "2023-07-01",
	end_date: "2023-11-31",
	logo: "https://safe.b68dev.xyz/m2hBnksN.jpeg",
	techstack: [
		"AWS",
		"NodeJS",
		"Typescript",
		"Rust",
		"MongoDB",
		"PostgreSQL",
		"Redis",
		"Docker",
		"EC2",
		"S3",
		"Lambda",
		"Infra Design",
	],
	website: "https://saasden.club/",
	info: "One dashboard for all your SaaS subscriptions | Reimagining SaaS Management",
};
export const description1 =
	"I am Jyotirmoy Bandyopadhayaya, AKA Bravo68web, 20, a student developer from India with passion in API and microservices development. I have expertice in DevOps and Full Stack development. I am a self taught developer and I am always looking for new challenges to learn and grow.";
export const description2 =
	"I love Cats 😻 and I love to code and I love to play FPS shooting games.";
export const LanguagesKnown = [
	"NodeJS",
	"Python",
	"C++",
	"C",
	"SQL",
	"Rust",
	"Go",
	"Bash",
	"Java",
	"Docker",
	"AWS",
	"GCP",
	"TypeScript",
	"Cloud Computing",
	"Git",
	"Linux",
	"NextJS",
];

export const LanguagesKnownCategory = [
	{ NodeJS: "#026F01" },
	{ Python: "#3776AB" },
	{ "C++": "#CE3074" },
	{ C: "#5A5EA7" },
	{ SQL: "#FFCD00" },
	{ Rust: "#E02021" },
	{ Go: "#BFD641" },
	{ Bash: "#010100" },
	{ Java: "#FFCD00" },
	{ Docker: "#00b7ff" },
	{ AWS: "#00A591" },
	{ TypeScript: "#FFCD00" },
	{ GCP: "#94DFE3" },
	{ "Cloud Computing": "#E00198" },
	{ Git: "#DD4132" },
	{ Linux: "#010100" },
	{ NextJS: "#010100" },
];

export const arts = [
	{
		name: "Karyl #1",
		type: "art",
		description: "Drawn Princess Connect : Re-Dive charecter #1",
		image: "/images/art/karyl-2-final-3b.png",
		url: "/images/art/karyl-2-final-3b.png",
	},
	{
		name: "Karyl #2",
		type: "art",
		description: "Drawn Princess Connect : Re-Dive charecter #2",
		image: "/images/art/karyl-2-final.png",
		url: "/images/art/karyl-2-final.png",
	},
	{
		name: "Ayaka",
		type: "art",
		description: "Drawing of Ayaka from the Genshin Impact game",
		image: "/images/art/H12M27S20.smoothed_careful.png",
		url: "/images/art/H12M27S20.smoothed_careful.png",
	},
	{
		name: "Kirby",
		type: "art",
		description: "Drawing of Kirby",
		image: "/images/art/Final_best.png",
		url: "/images/art/Final_best.png",
	},
];

export const extra = [
	{
		name: "PraiveBin",
		image: "/images/projects/privatebin.jpg",
		url: "https://paste.itsmebravo.dev/",
	},
	{
		name: "ImageSafe",
		image: "https://safe.b68dev.xyz/images/logo_smol.png",
		url: "https://safe.b68dev.xyz",
	},
	{
		name: "Bravo's Git Hosting",
		image: "https://gitea.io/images/gitea.png",
		url: "https://git.itsmebravo.dev/",
	},
	{
		name: "Bravo's Radio Player",
		image: "/images/projects/radio-cast.png",
		url: "https://radio.b68dev.xyz/",
	},
	{
		name: "Bravo's IRC",
		image: "/images/projects/irc.png",
		url: "https://irc.b68dev.xyz/",
	},
	{
		name: "IP Tracker",
		image: "/images/projects/GOIPTracker.png",
		url: "https://ip.b68dev.xyz",
	},
];

export const projects = [
	{
		name: "eeCTF",
		type: "project",
		description: "eeCTF - CTF Framework (in-development) ",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/encryptedge/eeCTF",
	},
	{
		name: "payment-page",
		type: "project",
		description: "Payment Page for EncryptEdge",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/encryptedge/payment-page",
	},
	{
		name: "pay-n-ticketing",
		type: "project",
		description: "RCS-CTF Ticketing System",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/encryptedge/pay-n-ticketing",
	},
	{
		name: "rcs-landing",
		type: "project",
		description: "RCS Landing page",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/encryptedge/rcs-landing",
	},
	{
		name: "zer0bin",
		type: "project",
		description: "Just a place to paste code ..",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/zer0bin",
	},
	{
		name: "coder",
		type: "project",
		description: "Provision remote development environments via Terraform",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/coder/coder",
	},
	{
		name: "npm-ez-dependency-adder",
		type: "project",
		description: "Easily install node dependencies on a single go",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/chirag3003/npm-ez-dependency-adder",
	},
	{
		name: "dashy",
		type: "project",
		description: "A self-hostable personal dashboard built for you.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/Lissy93/dashy",
	},
	{
		name: "vs-presence-server",
		type: "project",
		description: "This is a server that allows you to project your vscode presence to a custom rich presence server.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/vsc-presence-server",
	},
	{
		name: "Stockpile",
		type: "project",
		description: "Redis from Scratch using Nodejs [No External Dependencies] ",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/stockpile",
	},
	{
		name: "api-v1",
		type: "project",
		description: "My Old API",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/api-v1",
	},
	{
		name: "webrtc-call-app",
		type: "project",
		description: "WebRTC Video Call Application",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/webrtc-call-app",
	},
	{
		name: "stockpile-node-sdk",
		type: "project",
		description: "NodeJS SDK for Stockpile",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/stockpile-node-sdk"
	},
	{
		name: "emailengine-foss",
		type: "project",
		description: "FOSS Fork for EmailEmgine",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/emailengine-foss",
	},
	{
		name: "typescript-express-hasura-pgsql-template",
		type: "project",
		description: "A Template for a Typescript Express Server with Hasura and Postgres",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/typescript-express-hasura-pgsql-template"
	},
	{
		name: "cat-as-a-service",
		type: "project",
		description: "Cat as a Service API",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/gdsclpu/cat-as-a-service"
	},
	{
		name: "SHX",
		type: "project",
		description: "Shx is a platform ment to store and share files, images, text and URLs with ease.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/shx"
	},
	{
		name: "Enterprise Workspace Images [arm64]",
		type: "project",
		description: "Docker images [arm64] for use with Coder",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/enterprise-images",
	},
	{
		name: "Fixer Cache Builder",
		type: "project",
		description: "A Caching service to store Fixer Exchange Rates.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/fixer-cache-builder",
	},
	{
		name: "B68-CLI",
		type: "project",
		description: "A Command Line Application to interact with B68WEB API",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/b68-cli",
	},
	{
		name: "LPU MiniProject",
		type: "project",
		description:
			"Project Made for Summer Training MiniProject made by Jyotirmoy",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/lpu-summer-training-miniproject",
	},
	{
		name: "Another Quote Webapp",
		type: "project",
		description: "A web app that allows users to view and share quotes.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/another-quote-webapp",
	},
	{
		name: "Hello Tauri App",
		type: "project",
		description: "An basic hello tauri app",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/hello-tauri-app",
	},
	{
		name: "Osu! Score Embed",
		type: "project",
		description: "Embed osu! stats in Github Readme Profile",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/osu-score-embed",
	},
	{
		name: "WorkerBin (cf-challenge)",
		type: "project",
		description:
			"A Pastebin alternative, but it is using CF Worker API to store the data.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/cf-challenge",
	},
	{
		name: "Rust Shuttle",
		type: "project",
		description: "A Url Shortener microservice build with Rust",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/rust-shuttle-url-sh",
	},
	{
		name: "URL Minify",
		type: "project",
		description:
			"Simple URL shortener service that allows you to shorten any URL and redirect to the original URL.",
		image: "https://user-images.githubusercontent.com/41448663/153746139-237f8e4d-be25-4f04-91ec-2bb3ff6f0e34.png",
		url: "https://github.com/BRAVO68WEB/url-minify",
	},
	{
		name: "API",
		type: "project",
		description:
			"Bravo68web API solely devloped by me to provide a data on and needed by me on daily basis.",
		image: "/images/uptime-logo.png",
		url: "https://api.b68.dev/",
	},
	{
		name: "LPU Wifi Login",
		type: "project",
		description: "LPU Wifi Login Application to login to LPU Wifi network",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/lpu-wifi-login/main/icons/logo.png",
		url: "https://github.com/BRAVO68WEB/lpu-wifi-login",
	},
	{
		name: "LPU Live Chat",
		type: "project",
		description:
			"LPU Live Chat Application to chat with university students, teachers, etc..",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/lpu-live-chat/main/icons/logo.png",
		url: "https://github.com/BRAVO68WEB/lpu-live-chat",
	},
	{
		name: "Server Init Script",
		type: "project",
		description:
			"Server Init Script is a script to initialize the server and its services esp. Oracle Server",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/oracle-server-init",
	},
	{
		name: "GSSoC Website",
		type: "project",
		description: "Contributed to GSSoC website",
		image: "https://raw.githubusercontent.com/GSSoC-Web/gssoc-assets/main/Logos/GS_logo_Black.png",
		url: "https://github.com/girlscript/gssoc-website-new",
	},
	{
		name: "osu-spotify-yt-rest",
		type: "project",
		description:
			"osu-spotify-yt-rest is a REST API for connect osu! with Spotify and Youtube",
		image: "/images/projects/osu-project.jpg",
		url: "https://github.com/BRAVO68WEB/osu-spotify-yt-rest",
	},
	{
		name: "nodejs-auth-jwt-session",
		type: "project",
		description:
			"Made a NodeJS Authentication and JWT Session with Redis support",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/nodejs-auth-jwt-session",
	},
	{
		name: "simplify-cd",
		type: "project",
		description:
			"Made a CI/CD application to deploy any nodejs application",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/simplify-cd",
	},
	{
		name: "starship",
		type: "project",
		description: "Contributed to Starship project",
		image: "https://raw.githubusercontent.com/starship/starship/master/media/icon.png",
		url: "https://github.com/starship/starship",
	},
	{
		name: "qbadges",
		type: "project",
		description:
			"Made a npm package to fetch all the badges of a user from Qwiklabs",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/qbadges",
	},
	{
		name: "vscode-uipack",
		type: "project",
		description: "An Extension to make VSCode UI more beautiful",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/vscode-uipack/master/icon.png",
		url: "https://github.com/BRAVO68WEB/vscode-uipack",
	},
	{
		name: "vector-vscode-devpack",
		type: "project",
		description:
			"An Extension to make VSCode more efficient consisting of great extentions",
		image: "https://github.com/BRAVO68WEB/vector-vscode-devpack/blob/master/icon.png?raw=true",
		url: "https://github.com/BRAVO68WEB/vector-vscode-devpack",
	},
	{
		name: "IRC",
		type: "project",
		description: "Made a simple IRC web application",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/irc/master/client/src/icons/irc-icon.png",
		url: "https://github.com/BRAVO68WEB/irc",
	},
	{
		name: "propstar-theme",
		type: "project",
		description: "Made a theme for VSCode",
		image: "https://github.com/BRAVO68WEB/propstar-theme/raw/main/assets/icon.png",
		url: "https://github.com/BRAVO68WEB/propstar-theme",
	},
	{
		name: "yt-music-player",
		type: "project",
		description: "Made a YT Music Player",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/yt-music-player",
	},
	{
		name: "icyicons",
		type: "project",
		description: "Made a VSCode Iconpack",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/icyicons/master/icon.png",
		url: "https://github.com/BRAVO68WEB/icyicons",
	},
	{
		name: "lpu-ca1-python-proj",
		type: "project",
		description: "My University Python Project on Voice AI Assistant",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/lpu-ca1-python-proj",
	},
	{
		name: "img-proxy",
		type: "project",
		description: "An Image Proxy Server",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/img-proxy",
	},
	{
		name: "appsmith-docs",
		type: "project",
		description: "Contributed to Appsmith Documentation",
		image: "https://avatars.githubusercontent.com/u/67620218",
		url: "https://github.com/appsmithorg/appsmith-docs",
	},
	{
		name: "nodejs-image-upload-api",
		type: "project",
		description: "A NodeJS Image Upload API",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/chirag3003/nodejs-image-upload-api",
	},
	{
		name: "OwO",
		type: "project",
		description: 'A Multi-Lingual approach to print "OwO"',
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/OwO",
	},
	{
		name: "ImprovedTube",
		type: "project",
		description: "Contributed to ImprovedTube",
		image: "https://raw.githubusercontent.com/code-for-charity/YouTube-Extension/master/icons/128.png",
		url: "https://github.com/code-for-charity/YouTube-Extension",
	},
	{
		name: "Electron CPU meter",
		type: "project",
		description: "Created an Electron App to monitor CPU usage",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/electron-cpu-meter/master/src/icon.ico",
		url: "https://github.com/BRAVO68WEB/electron-cpu-meter",
	},
	{
		name: "LastFM DiscordRPC",
		type: "project",
		description: "LastFM + Discord RPC integration",
		image: "/images/brandlogos/Lastfm-icon-vector-03.svg",
		url: "https://github.com/BRAVO68WEB/lastfm-discordrpc",
	},
	{
		name: "Bin Buster",
		type: "project",
		description:
			"A simple, fast and useful bruter for multiple paste sources.",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/bin-buster",
	},
	{
		name: "LPU 2nd Sem Project",
		type: "project",
		description: "My University 2nd Sem Project on Web Development",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/lpu-2nd-sem-project",
	},
	{
		name: "Randomizer",
		type: "project",
		description:
			"A Random string encryptor w.r.t. Timestamps to add Security to your Web Application",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/Randomizer",
	},
	{
		name: "url-short-cfw",
		type: "project",
		description:
			"An Custom URL Shortener build on CloudFlare Worker Platform",
		image: "https://cdn.hashnode.com/res/hashnode/image/upload/v1624006530365/Ku95JYafL.jpeg",
		url: "https://github.com/BRAVO68WEB/url-short-cfw",
	},
	{
		name: "2048",
		type: "project",
		description:
			"An PWA instance of 2048 build with Javascript. Also added to KaiOS project",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/KaiOS-2048/main/assets/favicons/ms-icon-310x310.png",
		url: "https://github.com/BRAVO68WEB/2048",
	},
	{
		name: "MERN LPU HRD Project",
		type: "project",
		description: "An MERN Stack Project created for LPU HRD",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/mern-lpu-hrd-project",
	},
	{
		name: "Britta/discord-music-bot",
		type: "project",
		description: "Contributed to Britta Discord Music Bot (verified bot)",
		image: "https://raw.githubusercontent.com/b3h3m0th/britta_discord-music-bot/master/assets/img/brittaBanner.png",
		url: "https://github.com/b3h3m0th/britta_discord-music-bot",
	},
	{
		name: "Flutter Portfolio",
		type: "project",
		description: "My Portfolio made with Flutter Web framework",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/Portfolio-About",
	},
	{
		name: "Hexo Webnary Theme",
		type: "project",
		description: "A Fully Customised Hexo Flat Modular Theme",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/hexo-webnary-theme",
	},
	{
		name: "HOTEL_AND_TRANS_RES",
		type: "project",
		description: "Hotel and transportation reservation management",
		image: "/images/GitHub-Logo.png",
		url: "https://github.com/BRAVO68WEB/HOTEL_AND_TRANS_RES",
	},
	{
		name: "Hexo",
		type: "project",
		description: "Got my theme added to official Hexojs Community website",
		image: "https://raw.githubusercontent.com/hexojs/logo/master/hexo-logo-avatar.png",
		url: "https://github.com/hexojs/hexo",
	},
	{
		name: "Just-Some-Bots/MusicBot",
		type: "project",
		description: "Contributed to Just-Some-Bots/MusicBot",
		image: "https://avatars.githubusercontent.com/u/22779351",
		url: "https://github.com/Just-Some-Bots/MusicBot",
	},
	{
		name: "Github Profile Readme Generator",
		type: "project",
		description: "Contributed to Github Profile Readme Generator",
		image: "https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/mdg.png",
		url: "https://github.com/rahuldkjain/github-profile-readme-generator",
	},
	{
		name: "npm package - encrypted-randomizer",
		type: "project",
		description:
			"A Random string encryptor w.r.t. Timestamps to add Security to your Web Application",
		image: "https://raw.githubusercontent.com/npm/logos/master/npm%20logo/classic/npm-2009.png",
		url: "https://www.npmjs.com/package/encrypted-randomizer",
	},
	{
		name: "npm package - gen-dockerfile",
		type: "project",
		description: "Generate Dockerfile from Dockerfile.template",
		image: "https://raw.githubusercontent.com/npm/logos/master/npm%20logo/classic/npm-2009.png",
		url: "https://www.npmjs.com/package/gen-dockerfile",
	},
	{
		name: "npm package - qbadges",
		type: "project",
		description: "Generate badges for your GitHub profile",
		image: "https://raw.githubusercontent.com/npm/logos/master/npm%20logo/classic/npm-2009.png",
		url: "https://www.npmjs.com/package/qbadges",
	},
	{
		name: "npm package - @bravo68web/hexo-webnary-theme",
		type: "project",
		description: "Hexo Plugin for hexo-webnary-theme",
		image: "https://raw.githubusercontent.com/npm/logos/master/npm%20logo/classic/npm-2009.png",
		url: "https://www.npmjs.com/package/@bravo68web/hexo-webnary-theme",
	},
	{
		name: "Ampr Music",
		type: "project",
		description: "Made a simple music webapp",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/ampr-music/master/assets/logo.png",
		url: "https://github.com/BRAVO68WEB/ampr-music/",
	},
	{

	}
];

export const extraPages = [
	{
		name: "Qwiklabs Badges",
		type: "page",
		image: "/images/qwikilabs-logo.png",
		url: "/qbadges",
	},
	{
		name: "Status Page",
		type: "page",
		image: "/images/uptime-logo.png",
		url: "/status",
	},
	{
		name: "VSCode Extentions",
		type: "page",
		image: "/images/vscode-ext.png",
		url: "/vscode",
	},
	{
		name: "Game Skill Stats",
		type: "page",
		image: "/images/default_game.jpg",
		url: "/gameskills",
	},
	{
		name: "Something Special",
		type: "page",
		image: "/images/special.png",
		url: "/spl",
	},
];

export const vsExts = [
	{
		name: "icyicons",
		description: "Crystalify all your VSCode Icons.",
		type: "icon-pack",
		url: "https://marketplace.visualstudio.com/items?itemName=Bravo68web.icyicons",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/icyicons/master/icon.png",
	},
	{
		name: "propstar",
		description:
			"A multivariant VS-Code Theme build with ❤️. All theme designs and colour combinations are handpicked to suit every Programmers needs. Hope you love it.",
		type: "theme",
		url: "https://marketplace.visualstudio.com/items?itemName=Bravo68web.propstar",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/propstar-theme/main/assets/icon.png",
	},
	{
		name: "vscode-uipack",
		description: "VSCode UI Pack created by Bravo68web",
		type: "extentionPack",
		url: "https://marketplace.visualstudio.com/items?itemName=Bravo68web.vscode-uipack",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/vscode-uipack/master/icon.png",
	},
	{
		name: "vector-vscode-devpack",
		description: "Feature Rich VSCode Extension Pack created by Bravo68web",
		type: "extentionPack",
		url: "https://marketplace.visualstudio.com/items?itemName=Bravo68web.vector-vscode-devpack",
		image: "https://raw.githubusercontent.com/BRAVO68WEB/vector-vscode-devpack/master/icon.png",
	},
];

export const qwiklabs = [
	{
		title: "Implement DevOps in Google Cloud",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/953778",
		image: "https://cdn.qwiklabs.com/RGYLtQXngVN9TmGhbWvmyCTYdky3m3T9SZr7alsMcLg=",
	},
	{
		title: "Deploy to Kubernetes in Google Cloud",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/953549",
		image: "https://cdn.qwiklabs.com/SFfmObf8ridNvpy2+gn/azAh3SR4tXFTBhdKpT1Ocrc=",
	},
	{
		title: "Kubernetes in Google Cloud",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/953261",
		image: "https://cdn.qwiklabs.com/3cUZzotUhC3sWESWmiP9mofbB+cZrrX5NiKJEGZBS+4=",
	},
	{
		title: "Cloud Architecture",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/953041",
		image: "https://cdn.qwiklabs.com/I1ZuP3bdHif3qBweIZrUOJGvCOLDUARPSxhcuWLy3Lk=",
	},
	{
		title: "Build a Website on Google Cloud",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/952979",
		image: "https://cdn.qwiklabs.com/SsyJLaOyTv+j8kekVYpsQj3XkIEsZ6VrUwAA3TdrZLM=",
	},
	{
		title: "Website on Google Cloud",
		earnDate: "Earned May 21, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/952980",
		image: "https://cdn.qwiklabs.com/SH1cI5cBW/In5JzT/YwBsYDwtoiL8/IQynRtLER9ZXo=",
	},
	{
		title: "Deploy and Manage Cloud Environments with Google Cloud",
		earnDate: "Earned May 17, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/926988",
		image: "https://cdn.qwiklabs.com/z/6rqOh7o7nw7hj/1J/UXN8WSHYy4Zjka1F8Jc3xMBo=",
	},
	{
		title: "DevOps Essentials",
		earnDate: "Earned May 14, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/912916",
		image: "https://cdn.qwiklabs.com/0kN88wm9Jn/Ts6GNut2s2RhY/2vHs3jKLbL6MxZawqA=",
	},
	{
		title: "Network Performance and Optimization",
		earnDate: "Earned May 14, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/910858",
		image: "https://cdn.qwiklabs.com/9qikCAvRUMlQZkRAj3FqOQN00x3Jk+iA3QtkuhoRGvY=",
	},
	{
		title: "Create and Manage Cloud Resources",
		earnDate: "Earned May 14, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/909902",
		image: "https://cdn.qwiklabs.com/qigZkhvg9KqENz/VGMdHGLby/UQ+hr1id2Cbp0GxSvs=",
	},
	{
		title: "[DEPRECATED] Deploying Applications",
		earnDate: "Earned May 14, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/909030",
		image: "https://cdn.qwiklabs.com/1r8IzkgZ2ozf6jLcsKK81SdLwBzAL1f1vyuNmbXyhjE=",
	},
	{
		title: "Google Cloud Computing Foundations: Cloud Computing Fundamentals",
		earnDate: "Earned May 13, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/908100",
		image: "https://cdn.qwiklabs.com/X6BpQ/TB2C53JbD2SZyYekZHUSsJYXbyHeTf0Woudm4=",
	},
	{
		title: "Google Cloud Essentials",
		earnDate: "Earned May 13, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/dd51f4e2-6171-461b-888c-ce954832c72e/badges/908015",
		image: "https://cdn.qwiklabs.com/xRejIPM4k6VgI8++2Nz5bFHFx8PwK0nn9oQofkJOsS4=",
	},
	{
		title: "Intermediate ML: TensorFlow on Google Cloud",
		earnDate: "Earned Jun 18, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2273803",
		image: "https://cdn.qwiklabs.com/bn3X3Y3rVZT6kQP41qoGm/oHxKWxezmhyXowIZ1ColQ=",
	},
	{
		title: "Intro to ML: Language Processing",
		earnDate: "Earned Jun 18, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2273373",
		image: "https://cdn.qwiklabs.com/pP4Mzjwe7NsGoAvHEldwoJVwPCm0/OQ2EF/3ZrOi4f0=",
	},
	{
		title: "Google Cloud Solutions II: Data and Machine Learning",
		earnDate: "Earned Jun 18, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2271538",
		image: "https://cdn.qwiklabs.com/6QZdnTt3qeI52ubuaZ/UaGVhw2PJNj19D/GkCqHpZYE=",
	},
	{
		title: "Scientific Data Processing",
		earnDate: "Earned Jun 18, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2271060",
		image: "https://cdn.qwiklabs.com/f2K7LIxv+0qv5wRtdV42T89nfuB/6cxXZm+BOIjtsXA=",
	},
	{
		title: "Cloud SQL",
		earnDate: "Earned Jun 18, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2270680",
		image: "https://cdn.qwiklabs.com/LVLn2HMOHOqwpHFE+EQFON5KBbhpDJ+s/H3I+26GN6c=",
	},
	{
		title: "BigQuery for Marketing Analysts",
		earnDate: "Earned Jun 17, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2265875",
		image: "https://cdn.qwiklabs.com/wR2OjCC3caAXgdXzaRuQbgD+TU8pSxwY6m8CZFbef54=",
	},
	{
		title: "Applied Data: Blockchain",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2241467",
		image: "https://cdn.qwiklabs.com/gOBgtMPD6Vzqo3FH2fAfN0OmSRGhksEnZLxEldd9XMQ=",
	},
	{
		title: "NCAA® March Madness®: Bracketology with Google Cloud",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2241095",
		image: "https://cdn.qwiklabs.com//eGmk+n644/OaI+/G+xH2DgVBGJ7W4J63youTvLUMDI=",
	},
	{
		title: "Create ML Models with BigQuery ML",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2241071",
		image: "https://cdn.qwiklabs.com/8jACSR+qgI3p2yem69CxNAyXukexHsSAI5j2W71N+lc=",
	},
	{
		title: "BigQuery for Machine Learning",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2240973",
		image: "https://cdn.qwiklabs.com/J9Vhzq3bi1ZkIi0K8XD37yMRozJiWUpgnadzGeyUB6g=",
	},
	{
		title: "Build and Optimize Data Warehouses with BigQuery",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2237828",
		image: "https://cdn.qwiklabs.com/pvJAPKZACj9RvUOd1IuetIiUFGEfsuGZZMkQJaI0m20=",
	},
	{
		title: "BigQuery for Data Warehousing",
		earnDate: "Earned Jun 14, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2237577",
		image: "https://cdn.qwiklabs.com/8wZI+j18z5J5+HX7wspsQQSjLGGOlbQmx36HCAoLk/k=",
	},
	{
		title: "Engineer Data in Google Cloud",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2227376",
		image: "https://cdn.qwiklabs.com/KxYnffjiyPuh7QOen04Gtn09Y4B1Cb3YlWkwOYzCObc=",
	},
	{
		title: "Data Engineering",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2223122",
		image: "https://cdn.qwiklabs.com/+CsWnL49dO1EiQScypoKfAJdI8oWEgDWqu5PBt/Wepc=",
	},
	{
		title: "BigQuery Basics for Data Analysts",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2221997",
		image: "https://cdn.qwiklabs.com/bWAeRBJNl9ENT+//YwynddPswnVP9o2EtsDpMw4rVHc=",
	},
	{
		title: "Insights from Data with BigQuery",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2221904",
		image: "https://cdn.qwiklabs.com/Ob6sxQipL/04zO87+tO1xGhLBio6RiIYWAfwH+2+02g=",
	},
	{
		title: "Workspace: Add-ons",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2221465",
		image: "https://cdn.qwiklabs.com/6mwQS/shVpmYMnT1DM3N2WGuhTM9prhEU34z5GEtqQw=",
	},
	{
		title: "DEPRECATED IoT in the Google Cloud",
		earnDate: "Earned Jun 12, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2221184",
		image: "https://cdn.qwiklabs.com/4DkSNTJag2NYO5e+fBb28zb/f1VlN6fToz56Dedd8lQ=",
	},
	{
		title: "Cloud Development",
		earnDate: "Earned Jun 11, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2220255",
		image: "https://cdn.qwiklabs.com/tTcM/RANi25XfZdZfnAHBAPcD41qMCtwV6qnXwlH1ek=",
	},
	{
		title: "Serverless Cloud Run Development",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2202988",
		image: "https://cdn.qwiklabs.com/sNVqiyyYGBc7IfiWK6bF61rRXvzAtqUUYpM7bZkv8TU=",
	},
	{
		title: "Google Cloud Run Serverless Workshop",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2202734",
		image: "https://cdn.qwiklabs.com/lNja5KgIzUzVOwxZlR8/jM2w8LOIP4fkL2NN+xzCwPw=",
	},
	{
		title: "Exploring APIs",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2199226",
		image: "https://cdn.qwiklabs.com/Fcv56iHFhUUJ55ybE7WS0UNUNA0JbhYeqFvmkpFhvK8=",
	},
	{
		title: "Serverless Firebase Development",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2198596",
		image: "https://cdn.qwiklabs.com/MlsX6CARxRgoB1amY8s4of0erho3BhLX+kz3lBQYthY=",
	},
	{
		title: "Build Apps & Websites with Firebase",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2198432",
		image: "https://cdn.qwiklabs.com/JdUu8WCGmvzBQnppDxG/n1IoguiHNd0O/tdP3yWyv4Q=",
	},
	{
		title: "Build Interactive Apps with Google Assistant",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2197701",
		image: "https://cdn.qwiklabs.com/wqxQz1fDGoAkpW/DDijTordRtWY+Urol55r00wRH0Cc=",
	},
	{
		title: "OK Google: Build Interactive Apps with Google Assistant",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2197492",
		image: "https://cdn.qwiklabs.com/iN1Y1aBXjPPUZgDdv9GtQCf/Bp0q3U/Jg9uWO6RMKoc=",
	},
	{
		title: "Google Developer Essentials",
		earnDate: "Earned Jun  9, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2197353",
		image: "https://cdn.qwiklabs.com/V0I18jLPjGRqhwrDNn+I4YCq5rPoGX4lvg5DjqgwcJ0=",
	},
	{
		title: "Cloud Architecture: Design, Implement, and Manage",
		earnDate: "Earned Jun  8, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2196594",
		image: "https://cdn.qwiklabs.com/p3cSmWqrO0+x2NuFSET4XD1M/EMR24a7To+oAw1Q9S8=",
	},
	{
		title: "Monitor and Log with Google Cloud Operations Suite",
		earnDate: "Earned May 23, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2054787",
		image: "https://cdn.qwiklabs.com/ht3dxzalukepnESNH85pX/5ORl+yOrOBH2DoMJEoA7k=",
	},
	{
		title: "Build a Website on Google Cloud",
		earnDate: "Earned May 17, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2012479",
		image: "https://cdn.qwiklabs.com/SsyJLaOyTv+j8kekVYpsQj3XkIEsZ6VrUwAA3TdrZLM=",
	},
	{
		title: "Baseline: Deploy & Develop",
		earnDate: "Earned May 16, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2004846",
		image: "https://cdn.qwiklabs.com/hYiMA4VF+4Ud25kDvrO6jCax5PcuNyrURzlom/B3Emw=",
	},
	{
		title: "Website on Google Cloud",
		earnDate: "Earned May 16, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/2004513",
		image: "https://cdn.qwiklabs.com/SH1cI5cBW/In5JzT/YwBsYDwtoiL8/IQynRtLER9ZXo=",
	},
	{
		title: "Google Cloud's Operations Suite",
		earnDate: "Earned May  6, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1923812",
		image: "https://cdn.qwiklabs.com/dm0Hz9Vg2Nvvrsq3y1aCFz4xP1FoI6srK/qVJDqfdHo=",
	},
	{
		title: "Perform Foundational Infrastructure Tasks in Google Cloud",
		earnDate: "Earned May  2, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1900901",
		image: "https://cdn.qwiklabs.com/SOUHCWvev6HmfC5QztXJd+CkSK8+3WGWg+F/ww/fqXA=",
	},
	{
		title: "Understanding Your Google Cloud Costs",
		earnDate: "Earned May  2, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1900756",
		image: "https://cdn.qwiklabs.com/2GxKzUeZdj8jB1tlIej4wSVJ2V2INW5ea39KqWuRZzE=",
	},
	{
		title: "Build and Secure Networks in Google Cloud",
		earnDate: "Earned May  2, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1900473",
		image: "https://cdn.qwiklabs.com/fUkNC8Ujw5C3fdqhXntXppEGL+upKOgvE42GWf4Oo68=",
	},
	{
		title: "Google Cloud Solutions I: Scaling Your Infrastructure",
		earnDate: "Earned May  2, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1900095",
		image: "https://cdn.qwiklabs.com/ZJMZcere2fWYjqyr7gATsfmo9p7t2Hx/Gg0CCY3gLLU=",
	},
	{
		title: "Networking Fundamentals in Google Cloud ",
		earnDate: "Earned May  2, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1899984",
		image: "https://cdn.qwiklabs.com/07Ua8YRAr/1RypstXT/raoI72q+0IDzPoSsdnBfBmzY=",
	},
	{
		title: "Implement DevOps in Google Cloud",
		earnDate: "Earned May  1, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1890814",
		image: "https://cdn.qwiklabs.com/RGYLtQXngVN9TmGhbWvmyCTYdky3m3T9SZr7alsMcLg=",
	},
	{
		title: "Deploy to Kubernetes in Google Cloud",
		earnDate: "Earned May  1, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1890209",
		image: "https://cdn.qwiklabs.com/SFfmObf8ridNvpy2+gn/azAh3SR4tXFTBhdKpT1Ocrc=",
	},
	{
		title: "Set Up and Configure a Cloud Environment in Google Cloud",
		earnDate: "Earned May  1, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1889873",
		image: "https://cdn.qwiklabs.com/o/N83w0HEfVQYE3IF6A8C/BHph2rF/fkHlYZ51DWOr4=",
	},
	{
		title: "DevOps Essentials",
		earnDate: "Earned Apr 27, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1866507",
		image: "https://cdn.qwiklabs.com/0kN88wm9Jn/Ts6GNut2s2RhY/2vHs3jKLbL6MxZawqA=",
	},
	{
		title: "Kubernetes in Google Cloud",
		earnDate: "Earned Apr 27, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1866353",
		image: "https://cdn.qwiklabs.com/3cUZzotUhC3sWESWmiP9mofbB+cZrrX5NiKJEGZBS+4=",
	},
	{
		title: "Cloud Architecture",
		earnDate: "Earned Apr 27, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1863569",
		image: "https://cdn.qwiklabs.com/I1ZuP3bdHif3qBweIZrUOJGvCOLDUARPSxhcuWLy3Lk=",
	},
	{
		title: "Cloud Engineering",
		earnDate: "Earned Apr 26, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1862677",
		image: "https://cdn.qwiklabs.com/kuBgucU/wbX9lkaNZfxQERQoa411Wr1xJ88uoYbpgT0=",
	},
	{
		title: "Create and Manage Cloud Resources",
		earnDate: "Earned Apr 26, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1862537",
		image: "https://cdn.qwiklabs.com/qigZkhvg9KqENz/VGMdHGLby/UQ+hr1id2Cbp0GxSvs=",
	},
	{
		title: "Baseline: Infrastructure",
		earnDate: "Earned Apr 26, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1862458",
		image: "https://cdn.qwiklabs.com/Eg/SbOy66StYJSJgDWYLrHAMVb/28ZfyndLzHYtQPeA=",
	},
	{
		title: "Google Cloud Essentials",
		earnDate: "Earned Apr 26, 2022 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/d541db65-d9a1-4e89-9c16-0f2f98de84a4/badges/1862284",
		image: "https://cdn.qwiklabs.com/xRejIPM4k6VgI8++2Nz5bFHFx8PwK0nn9oQofkJOsS4=",
	},
	{
		title: "Engineer Data in Google Cloud",
		earnDate: "Earned Oct 12, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1336298",
		image: "https://cdn.qwiklabs.com/KxYnffjiyPuh7QOen04Gtn09Y4B1Cb3YlWkwOYzCObc=",
	},
	{
		title: "Insights from Data with BigQuery",
		earnDate: "Earned Oct 10, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1324551",
		image: "https://cdn.qwiklabs.com/Ob6sxQipL/04zO87+tO1xGhLBio6RiIYWAfwH+2+02g=",
	},
	{
		title: "Deploy and Manage Cloud Environments with Google Cloud",
		earnDate: "Earned Oct 10, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1322744",
		image: "https://cdn.qwiklabs.com/z/6rqOh7o7nw7hj/1J/UXN8WSHYy4Zjka1F8Jc3xMBo=",
	},
	{
		title: "Build and Secure Networks in Google Cloud",
		earnDate: "Earned Oct  8, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1300339",
		image: "https://cdn.qwiklabs.com/fUkNC8Ujw5C3fdqhXntXppEGL+upKOgvE42GWf4Oo68=",
	},
	{
		title: "Deploy to Kubernetes in Google Cloud",
		earnDate: "Earned Oct  7, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1295426",
		image: "https://cdn.qwiklabs.com/SFfmObf8ridNvpy2+gn/azAh3SR4tXFTBhdKpT1Ocrc=",
	},
	{
		title: "Set Up and Configure a Cloud Environment in Google Cloud",
		earnDate: "Earned Oct  6, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1284996",
		image: "https://cdn.qwiklabs.com/o/N83w0HEfVQYE3IF6A8C/BHph2rF/fkHlYZ51DWOr4=",
	},
	{
		title: "Perform Foundational Infrastructure Tasks in Google Cloud",
		earnDate: "Earned Oct  4, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1267552",
		image: "https://cdn.qwiklabs.com/SOUHCWvev6HmfC5QztXJd+CkSK8+3WGWg+F/ww/fqXA=",
	},
	{
		title: "Integrate with Machine Learning APIs",
		earnDate: "Earned Oct  2, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1252426",
		image: "https://cdn.qwiklabs.com/h/CMZVTG3/g7X2zuSD5nF2/GTVTrwrgQ6cWd6G6THFg=",
	},
	{
		title: "DEPRECATED Explore Machine Learning Models with Explainable AI",
		earnDate: "Earned Sep 27, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1221140",
		image: "https://cdn.qwiklabs.com/0bSya3/5VLUuF1UhSN5g8ARZbhzm24GCBuxZ/NeuSzw=",
	},
	{
		title: "Perform Foundational Data, ML, and AI Tasks in Google Cloud",
		earnDate: "Earned Sep 26, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1212441",
		image: "https://cdn.qwiklabs.com/+fUNwBxkIaRRdkzbDGS6GW+BbMbyXO6F+Jg+3QrSXeA=",
	},
	{
		title: "Create and Manage Cloud Resources",
		earnDate: "Earned Sep 25, 2021 EDT",
		url: "https://www.cloudskillsboost.google/public_profiles/293e000c-f58c-4119-b60b-e0e7a769e61f/badges/1208738",
		image: "https://cdn.qwiklabs.com/qigZkhvg9KqENz/VGMdHGLby/UQ+hr1id2Cbp0GxSvs=",
	},
];
